version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ../data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8086:8080

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9007:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mysql:
    env_file:
      - ./env/mysql.env
    image: mysql:5.7
    restart: always
    command: --max_allowed_packet=32505856 --sql_mode=""
    ports:
      - 3317:3306
    volumes:
      - ../data/mysql:/var/lib/mysql

  phpmyadmin:
    env_file:
      - ./env/mysql.env
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8008:80

  registry:
    restart: always
    image: registry:latest
    ports:
      - 5001:5000
    volumes:
      - ./configs/registry/config.yml:/etc/docker/registry/config.yml:ro
      - ../data/registry:/var/lib/registry:rw

  gitserver:
    env_file:
      - ./env/gitserver.env
    image: gitea/gitea:1.14.1
    restart: always
    networks:
      - gitea
    volumes:
      - ../data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3001:3000
      - 222:22
    depends_on:
      - gitdb

  gitdb:
    env_file:
      - ./env/gitdb.env
    image: mysql:5.7
    restart: always
    networks:
      - gitea
    volumes:
      - ../data/gitdb:/var/lib/mysql

networks:
  gitea:
    external: false

volumes:
  portainer_data:
