version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8086:8080"

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9007:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mysql:
    image: mysql:5.7
    restart: always
    command: --max_allowed_packet=32505856 --sql_mode=""
    ports:
      - 3317:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=database

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8008:80'
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root_password

  registry:
    restart: always
    image: registry:latest
    ports:
      - 5001:5000
    volumes:
      - ./configs/registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./data/registry:/var/lib/registry:rw

  gitserver:
    image: gitea/gitea:1.14.1
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__TYPE=mysql
      - GITEA__database__HOST=gitdb:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
      - "222:22"
    depends_on:
      - gitdb

  gitdb:
    env_file:
      - ./env/gitdb.env
    image: mysql:5.7
    restart: always
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  backend:
    external: false
  gitea:
    external: false

volumes:
  portainer_data:
